# Generated by Django 3.1.1 on 2020-10-17 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the punters name', max_length=200)),
                ('external_id', models.IntegerField(help_text='Enter the golf channel event id')),
            ],
        ),
        migrations.CreateModel(
            name='Golfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the golfers name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Punter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the punters name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfpicks.event')),
                ('picks', models.ManyToManyField(help_text='Select golfer picks', to='golfpicks.Golfer')),
                ('punter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfpicks.punter')),
            ],
        ),
    ]
