# Generated by Django 3.1.1 on 2020-10-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfpicks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golfer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='punter',
            options={'ordering': ['name']},
        ),
    ]
